site_name: SN Wiki
docs_dir: ..
site_dir: ../../site
theme:
  name: 'readthedocs'
  custom_dir: 'theme'
  navigation_depth: 2
  logo: '.images/SN White Text Logo.png'
repo_url: https://github.com/FRCTeam3255/Wiki
edit_uri: https://github.com/FRCTeam3255/Wiki/edit/main/
site_author: Tayler Uva
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
exclude_docs: |
  !.images